### ISSUE TITLE
Provide HTTP Status Code in Error object for failure closures

### ISSUE THREAD

**Issue by ghost** [RedP4nda/RPHTTPServiceClient#3]
Hi,

When we pass in the block failure as in the code below it would be nice to have the status of the error for more traceability (401,403,501,503 etc....)

`
        _ = super.requestObject(target: target, success: { (val : valueDTO) in
        }, failure: { (error) in
            print(error)
        })
`

Thanks

**Comment by MrCloud** [comment]
Hello @Vincent-Valembois, 
As error occurs with various causes (invalid JSON, HTTP 5xx code, HTTP 4xx code, network failure) here's how you will be able to check for statusCodes in failures (make sure you use RPHTTPServiceClient version 0.10.x) :

```swift 
_ = super.requestObject(target: target, success: success) { (error) in
            switch error {
            case .RequestError(let statusCode, let json):
                print("Error occured with statusCode: \(statusCode), error: \(json)")
            case .JSONParsing(let cause):
                print(cause)
            case .InvalidMapping(let json):
                print(json)
            case .RequestFailure(let statusCode, let cause):
                print("cause: \(cause)")
            }
```
